-- Execute este script no SQL Editor do Supabase para habilitar a contagem de leituras para todos os usuários (logados e não logados).

-- 1. Garante que a coluna scan_count existe na tabela targets e inicia com 0
ALTER TABLE targets 
ADD COLUMN IF NOT EXISTS scan_count INTEGER DEFAULT 0;

-- 2. Cria a tabela scan_logs se não existir (para garantir)
CREATE TABLE IF NOT EXISTS scan_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT REFERENCES targets(id) ON DELETE CASCADE,
    scanned_at TIMESTAMPTZ DEFAULT NOW(),
    scanner_ip TEXT -- Opcional, para evitar flood
);

-- 3. Habilita RLS na tabela scan_logs
ALTER TABLE scan_logs ENABLE ROW LEVEL SECURITY;

-- 4. Permite inserção para TODOS (anônimos e logados)
-- Remove política antiga se existir para evitar conflito
DROP POLICY IF EXISTS "Enable insert for all users" ON scan_logs;

CREATE POLICY "Enable insert for all users"
ON scan_logs FOR INSERT
TO public
WITH CHECK (true);

-- 5. Função para incrementar o contador automaticamente
CREATE OR REPLACE FUNCTION increment_target_scan_count()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE targets
  SET scan_count = COALESCE(scan_count, 0) + 1
  WHERE id = NEW.target_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Trigger que dispara a função acima ao inserir um log
DROP TRIGGER IF EXISTS on_scan_log_insert ON scan_logs;

CREATE TRIGGER on_scan_log_insert
AFTER INSERT ON scan_logs
FOR EACH ROW
EXECUTE FUNCTION increment_target_scan_count();
